apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::686226804600:role/UdacityFlaskDeployCBKubectlRole
      username:build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::686226804600:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-14C8EKR3J71RZ
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-12T20:26:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1256"
  uid: ac354f46-0689-4a7a-9961-442e9482e7ba
